// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_21d1moFBd9AdVfRuM6YAzhiXCi8yco',
    appId: '1:812428249974:web:75115e141122ba1fb24857',
    messagingSenderId: '812428249974',
    projectId: 'solidarity-135d8',
    authDomain: 'solidarity-135d8.firebaseapp.com',
    storageBucket: 'solidarity-135d8.appspot.com',
    measurementId: 'G-KZWM1FEHY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWin5rWnFEsGQloBR1x_g3WYhAlby3w-w',
    appId: '1:812428249974:android:bb6a3ee19bde218bb24857',
    messagingSenderId: '812428249974',
    projectId: 'solidarity-135d8',
    storageBucket: 'solidarity-135d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMp4mkJTamdvT4rUxWbmBsNoWHsg89NNk',
    appId: '1:812428249974:ios:4fb99a238a1755f3b24857',
    messagingSenderId: '812428249974',
    projectId: 'solidarity-135d8',
    storageBucket: 'solidarity-135d8.appspot.com',
    iosBundleId: 'com.example.solidarity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMp4mkJTamdvT4rUxWbmBsNoWHsg89NNk',
    appId: '1:812428249974:ios:4fb99a238a1755f3b24857',
    messagingSenderId: '812428249974',
    projectId: 'solidarity-135d8',
    storageBucket: 'solidarity-135d8.appspot.com',
    iosBundleId: 'com.example.solidarity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg_21d1moFBd9AdVfRuM6YAzhiXCi8yco',
    appId: '1:812428249974:web:01446b1f612645adb24857',
    messagingSenderId: '812428249974',
    projectId: 'solidarity-135d8',
    authDomain: 'solidarity-135d8.firebaseapp.com',
    storageBucket: 'solidarity-135d8.appspot.com',
    measurementId: 'G-RF0NC73Q5S',
  );

}